<?xml version="1.0" encoding="utf-8"?><Database Name="CursoLINQ" Class="PruebaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LENOVOM95\SQLEXPRESS;Initial Catalog=CursoLINQ;Integrated Security=True" SettingsObjectName="BDEmpleados.Properties.Settings" SettingsPropertyName="CursoLINQConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Empleado" Member="Empleado">
    <Type Name="Empleado">
      <Column Name="CODIGO" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="NOMBRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="APPATERNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="APMATERNO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EDAD" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>