// <auto-generated />
namespace WebAppCurso6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Alumnos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Alumnos));
        
        string IMigrationMetadata.Id
        {
            get { return "202306192223433_Alumnos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
